### ISSUE TITLE
C2027 compilation error vkpp::CommandBuffer and vkpp::CommandPool

### ISSUE THREAD

**Issue by kirdaybov** [CaffeineViking/vkhr#53]
Followed the compilation guide on Win10 with Visual Studio 2019 and got these compilation errors. Both in Release and Debug.
![image](https://user-images.githubusercontent.com/6114638/120939502-5e315080-c6e6-11eb-8030-34da49ae9d8a.png)

It doesn't look like the author intended to provide definitions for these headers because forward declarations are in place. Judging by the message "This diagnostic occurred in the compiler generated function" that doesn't show any specific source it seems like the compiler tried to compile it by itself (not clear with what type as T though).

Any ideas what could be the issue?

**Comment by CaffeineViking** [comment]
Sounds nasty... I remember there being some cyclic dependency when I was writing it (which I stupidly just ignored back then).

**Comment by CaffeineViking** [comment]
I'll try to dedicate a couple of days to look into the issues in `vkhr` during the summer (that NVIDIA crash looked nasty as well).

**Comment by CaffeineViking** [comment]
@kirdaybov easiest work around would be to disable [two-phase name lookup](https://docs.microsoft.com/en-us/cpp/build/reference/zc-twophase?view=msvc-160) with `/Zc:twoPhase-` (we had issues at work too).

**Comment by kirdaybov** [comment]
Thanks, the workaround helped!

**Comment by CaffeineViking** [comment]
I've disabled it by default now.
